name: CD Staging

on:
#  push:
#    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'         
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install awscurl

    - name: Deploy Staging
      id: deployStaging
      shell: bash
      env:
        BODY: "{\"environment\":\"stg\",\"version\":\"${{ github.event.inputs.version }}\"}"
        AWS_BUILD_API: $ {{ secrets.VBR_AWS_BUILD_API }}
        AWS_BUILD_USER_ACCESS_KEY_ID: ${{ secrets.VBR_AWS_BUILD_USER_ACCESS_KEY_ID }}
        AWS_BUILD_USER_SECRET_ACCESS_KEY: ${{ secrets.VBR_AWS_BUILD_USER_SECRET_ACCESS_KEY }}
      run: echo RESPONSE=awscurl --access_key $AWS_BUILD_USER_ACCESS_KEY_ID --secret_key $AWS_BUILD_USER_SECRET_ACCESS_KEY --region eu-west-1 --service execute-api -X POST -d $BODY $AWS_BUILD_API/streetname-registry-api

    - name: Show Response
      run: |
        echo ${{ fromJSON(steps.deployStaging.outputs.response).status }}
        echo ${{ fromJSON(steps.deployStaging.outputs.response).body.BuildUuid }}