name: CD Staging

on:
#  push:
#    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: sample
      env:
        BUILD_URL: ${{ secrets.VBR_AWS_BUILD_API }}/streetname-registry-api
        STATUS_URL: ${{ secrets.VBR_AWS_BUILD_STATUS_API }}/streetname-registry-api
      uses: informatievlaanderen/awscurl-polling-action@main
      with:
          environment: stg
          version: ${{ github.event.inputs.version }}
          status-url: $STATUS_URL
          deploy-url: $BUILD_URL
          access-key: ${{ secrets.VBR_AWS_BUILD_USER_ACCESS_KEY_ID }}
          secret-key: ${{ secrets.VBR_AWS_BUILD_USER_SECRET_ACCESS_KEY }}
          region: eu-west-1
          interval: 2
