name: Testje 2

on:
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'Informatievlaanderen'
    name: Build
    runs-on: ubuntu-latest
#    outputs:
#      version: ${{ steps.set-version.outputs.version }}

    steps:
    - name: Get hello-world
      shell: bash
      run: docker pull hello-world

     #
     # Save artifacts
     #
      
    - name: Save hello-world
      shell: bash
      run: docker image save $BUILD_DOCKER_REGISTRY/streetname-registry/hello-world:99.99.0 -o ~/sr-hello-world-image.tar
      env:
        BUILD_DOCKER_REGISTRY: ${{ secrets.VBR_BUILD_DOCKER_REGISTRY_TST }}
        
    #
    # Upload artifacts
    #
        
    - name: Upload hello-world artifact
      if: env.RELEASE_VERSION != 'none'
      uses: actions/upload-artifact@v3
      with:
        name: hello-world
        path: ~/sr-hello-world-image.tar

#  test: # deploy to TEST environment
#    uses: ./.github/workflows/test.yml
#    with:
#      version: env.RELEASE_VERSION

  push_images_to_test:
    needs: build
    name: Push hello-world to Test
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials (Test)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.VBR_AWS_ACCESS_KEY_ID_TST }}
          aws-secret-access-key: ${{ secrets.VBR_AWS_SECRET_ACCESS_KEY_TST }}
          aws-region: ${{ secrets.VBR_AWS_REGION_PRD }}

      - name: Login to Amazon ECR (Test)
        uses: aws-actions/amazon-ecr-login@v1.5.1

      #
      # Download artifacts
      #
      
      - name: Download hello-world
        uses: actions/download-artifact@v3
        with:
          name: hello-world
          path: ~/

      #
      # Load artifacts
      #
      
      - name: Load hello-world image
        shell: bash
        run: docker image load -i ~/sr-hello-world-image.tar

      - name: Push docker images to ECR Test
        shell: bash
        run: |
          docker push $BUILD_DOCKER_REGISTRY/streetname-registry/hello-world:$SEMVER
        env:
          BUILD_DOCKER_REGISTRY: ${{ secrets.VBR_BUILD_DOCKER_REGISTRY_TST }}
          WORKSPACE: ${{ github.workspace }}
